import type Instancia from "./instancia";
import type { MovimentacaoTuple } from "./movimentacao";
import type NaturezaDg from "./naturezaDg";
import type ProcessoRelacionado from "./processoRelacionado";

export default interface Processo {
  processoId: number;
  numero: string;
  numeroAlternativo: string;
  anexos?: any[];
  vara: string;
  vara_original: string;
  classeNatureza: string;
  classeNatureza_dg: NaturezaDg;
  movs?: MovimentacaoTuple[];
  distribuicaoTipo: string;
  situacao: string;
  juiz?: string;
  area: string;
  assuntoExtra: string;
  audiencias: string[][];
  extinto: number;
  valor?: number;
  alteradoEm?: Date;
  foro: string;
  foro_cnj: string;
  regional_cnj?: boolean;
  situacao_situacaoID?: number;
  sentencaData?: Date;
  comarca: string;
  comarca_cnj: string;
  tribunalID: number;
  tribunal: string;
  processoID: number;
  distribuicaoData: Date;
  arquivado: boolean;
  classes: any[];
  classes_cnj: any[];
  acessos: Date[];
  uf: string;
  criadoEm: Date;
  partes?: any[];
  instancia: Instancia;
  fonte_sistema: string;
  polo: number;
  flag: number;
  processosRelacionados: ProcessoRelacionado[];
  liminar?: boolean;
  gratuita?: boolean;
  segredo_justica: boolean;
}
