export type TipoAndamentoTuple = [number, number];

export default class TipoAndamento {
  constructor(public tipo: string, public subtipo?: string) {}

  static parseTuple(tuple: [number, number]) {
    const key = `(${tuple[0]}, ${tuple[1]})`;
    const levels = (mapaTipos[key] as string).split(" - ");
    const subtipo = levels.length > 1 ? levels[1] : undefined;
    return new TipoAndamento(levels[0], subtipo);
  }
}
const mapaTipos: any = {
  "(0, 0)": "Desconhecido",
  "(1, 1)": "Agravo de Instrumento Interposto",
  "(2, 1)": "Audiência - Designada",
  "(2, 2)": "Audiência - Redesignada",
  "(2, 3)": "Audiência - Outros",
  "(2, 4)": "Audiência - Cancelada",
  "(3, 1)": "Deferida - Citação",
  "(3, 2)": "Deferida - conversao de busca e apreensão em execucao",
  "(3, 3)": "Deferida - liminar recolhimento custas",
  "(3, 4)": "Deferida - liminar teor",
  "(3, 5)": "Deferido - arquivamento",
  "(3, 6)": "Deferido - bloqueio bem",
  "(3, 7)": "Deferido - pedido de penhora",
  "(3, 8)": "Deferido - suspensão 921",
  "(3, 9)": "Deferido - sobrestamento",
  "(3, 10)": "Deferida - liminar em parte",
  "(4, 0)": "Manifestacao contestacao - outros",
  "(4, 1)": "Contatar Of.Just. mandado deferido",
  "(4, 2)": "Contestação manifestacao réu",
  "(5, 1)": "Desbloqueado veiculo Detran",
  "(6, 1)": "Extinção - sem Mérito I",
  "(6, 2)": "Extinção - sem Mérito II",
  "(6, 3)": "Extinção - sem Mérito III",
  "(6, 4)": "Extinção - sem Mérito VI",
  "(6, 5)": "Extinção - outros",
  "(7, 1)": "Homologada a desistência 485 VIII",
  "(7, 2)": "Homologado acordo suspenso",
  "(7, 3)": "Homologo acordo 487",
  "(8, 1)": "Indeferida a Liminar",
  "(9, 1)": "Informa Núm.proc. e vara",
  "(11, 1)": "Juntar - minuta de acordo",
  "(11, 2)": "Juntar - planilha debito",
  "(12, 1)": "Levantar deposito judicial",
  "(13, 0)": "Manifestar nos autos - outros",
  "(13, 1)": "Manifestar autor - Andamento Feito",
  "(13, 2)": "Manifestar autor - Certidão Oficial de Justiça",
  "(14, 0)": "Manifestar provas - outros",
  "(14, 1)": "Produção de provas",
  "(15, 1)": "Recolher custas - diligencia Of.Just.",
  "(15, 2)": "Recolher custas - outros",
  "(16, 1)": "Retirar oficios",
  "(17, 1)": "Sentença - Procedente",
  "(17, 2)": "Sentença - Improcedente",
  "(17, 3)": "Sentença - Parcialmente procedente",
  "(18, 1)": "Transitado em julgado",
  "(19, 0)": "Manifestar oficio - outros",
  "(19, 1)": "Verificar resposta oficios",
  "(20, 1)": "Iniciada - Liquidação",
  "(20, 2)": "Iniciada - Execução",
  "(21, 0)": "Publicacao - outros",
  "(21, 1)": "Publicação realizada",
  "(21, 2)": "Expedição comunicação via sistema",
  "(22, 1)": "Expedido alvará ao réu",
  "(22, 2)": "Alvará e deposito",
  "(23, 0)": "Disponibilizada intimacao - outros",
  "(23, 1)": "Disponibilizada a Intimação",
  "(24, 1)": "Expedida Notificação",
  "(25, 0)": "Acórdão",
  "(25, 1)": "Publicado o Acórdão",
  "(26, 1)": "Conhecido o recurso - não provido",
  "(27, 1)": "Incluído em pauta",
  "(28, 1)": "Revelia",
  "(29, 0)": "Manifestar reu - outros",
  "(29, 1)": "Manifestar réu",
  "(30, 0)": "Expedida intimacao - outros",
  "(30, 1)": "Citacao - Positiva",
  "(30, 2)": "Citacao - Intimação expedida",
  "(30, 3)": "Citacao - Citação expedida",
  "(31, 2)": "Citacao - AR negativo juntado",
  "(32, 1)": "Prazo decorrido",
  "(33, 1)": "Gratuidade - Deferida",
  "(33, 2)": "Gratuidade - Indeferida",
  "(34, 1)": "Antecipação de Tutela - Concedida",
  "(34, 2)": "Antecipação de Tutela - Não concedida",
  "(35, 1)": "Carta precatória - Expedição",
  "(36, 1)": "Mandado - Expedição",
  "(38, 1)": "Ofício requisitorio",
  "(39, 1)": "Contadoria",
  "(41, 1)": "Decurso de prazo",
};
